config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "home#index"

  get "ticket/:id/mail/:email", to: "tickets#show", as: "email_ticket"
  get "edit_ticket/:id/mail/:email", to: "tickets#edit", as: "edit_email_ticket"
  resources :tickets do
    member do
      resource :comment
      get "load_next_comments", to: "comments#get_next_ticket_comments", as: "get_next_ticket_comments"
      get "load_next_history", to: "tickets#get_next_ticket_history", as: "get_next_ticket_history"
    end
  end

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  before_validation :set_default_status, on: :create
  before_save :set_ticket_history
  validates_presence_of :user_name, :email, :title, :text, :problem_type_id, :status_id
  belongs_to :problem_type
  belongs_to :status
  belongs_to :admin_user



  scope :user_tickets, ->(user_email) {where(email: user_email)}
  scope :all_tickets, -> {}

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :ticket_histories, dependent: :destroy

  accepts_nested_attributes_for :comments, :allow_destroy => true

  if Status.all.count > 0
    Status.all.each do |status|
      scope status.name.to_sym, ->{where(status_id: status.id)}
    end
  end

  if ProblemType.all.count > 0
    ProblemType.all.each do |type|
      scope type.name.to_sym, ->{where(problem_type_id: type.id)}
    end
  end


  def get_histories
    self.ticket_histories.order(created_at: :desc)
  end

  private
  def set_ticket_history
    if self.new_record?
      self.ticket_histories.new(action_name: "create ticket", admin_user_id: self.admin_update_id ? self.admin_update_id : nil)
    else
      self.ticket_histories.new(action_name: "edit ticket", admin_user_id: self.admin_update_id ? self.admin_update_id : nil) if self.changed?
    end
  end

  def set_default_status
    self.status_id = Status.costumer_default.first.id
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  respond_to :html


  before_action :get_ticket, only: [:show, :edit, :update, :get_next_ticket_history]

  before_action :check_ticket_owner, only: [:show, :edit]

  before_action :get_user_tickets, only: [:index]

  def index
    add_dashboard_breadcrumb
  end

  def new
    add_dashboard_breadcrumb
    add_breadcrumb 'Create ticket', :new_ticket_path, prepend: '<i class="fa fa-edit"></i> '
    @ticket = Ticket.new
  end

  def show
    add_dashboard_breadcrumb
    add_breadcrumb 'Ticket', email_ticket_path(@ticket.id, email_param), prepend: '<i class="fa fa-user"></i> '
    add_breadcrumb 'Edit', edit_email_ticket_path(@ticket.id, email_param), prepend: '<i class="fa fa-edit"></i> '
    @comment = Comment.new
    @comments = @ticket.comments.order(created_at: :desc).limit(5)
    @ticket_histories = @ticket.get_histories.limit(5)
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      flash[:notice] = "Saved successfully"
      AdminMailer.new_ticket_created(@ticket).deliver_later
      UserMailer.new_ticket_created(@ticket).deliver_later
      redirect_to email_ticket_path(@ticket.id, @ticket.email.gsub(".", "_"))
    else
      flash.now[:alert] = @ticket.errors.full_messages.join(", ")
      render :new
    end
  end


  def edit
    add_dashboard_breadcrumb
    add_breadcrumb 'Ticket', email_ticket_path(@ticket.id, email_param), prepend: '<i class="fa fa-user"></i> '
    add_breadcrumb 'Edit', edit_email_ticket_path(@ticket.id, email_param), prepend: '<i class="fa fa-edit"></i> '
  end


  def update
    if @ticket.update_attributes(ticket_params.merge!(admin_update_id: nil))
      flash[:notice] = "Updated successfully"
      redirect_to email_ticket_path(@ticket.id, @ticket.email.gsub(".", "_"))
    else
      flash.now[:alert] = @ticket.errors.full_messages.join(", ")
      render :edit
    end
  end

  def get_next_ticket_history
    @next_histories = @ticket.get_histories.offset(params[:history_count]).limit(5)
    respond_to :js
  end

  private

  def ticket_params
    params.require(:ticket).permit(:admin_update_id, :user_name, :email, :title, :text, :problem_type_id, :status_id)
  end

  def get_user_tickets
    @tickets = Ticket.user_tickets(params[:email].gsub("_", ".")).order(created_at: :desc).paginate(page: params[:page], per_page: 10) if params[:email]
    get_last_tickets_comments
  end

  def get_last_tickets_comments
    # @last_comments = Comment.where(commentable_type: "Ticket", commentable_id: @tickets.pluck(:id)).last(5) if params[:email]
    @last_comments = @tickets.each.map{|ticket| ticket.comments.last }.compact if params[:email]
    p "@last_comments"
    p @last_comments
  end

  def check_ticket_owner
    if @ticket.email.gsub(".", "_") != params[:email]
      render :file => "#{Rails.root}/public/404", :layout => false, :status => 404
    end
  end



end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_ticket_form.html.haml
.form-group
  =f.label :email
  =f.email_field :email, class: "form-control"
.form-group
  =f.label :user_name
  =f.text_field :user_name, class: "form-control"
.form-group
  =f.label :problem_type_id
  =f.select :problem_type_id, options_from_collection_for_select(ProblemType.active_problem_types, "id", "name"), {prompt: "Select Problem Type"}, class: "form-control"
.form-group
  =f.label :title
  =f.text_field :title, class: "form-control"
.form-group
  =f.label :text
  =f.text_area :text, class: "form-control"

app/views/tickets/_ticket_history_line.html.haml
.history_line
  .well
    -if history.admin_user_id
      =history.admin_user.email
    -else
      -if history.admin_user_id
        =history.ticket.admin_user.email
      -else
        =history.ticket.email
    .well.history_action_info
      =history.action_name
      .pull-right
        =history.created_at.strftime("%d-%m-%Y")

app/views/tickets/edit.html.haml
-content_for :page_header do
  Create Ticket
-content_for :sub_header do
  New ticket page
-content_for :current_page_breadcrumb do
  %i.fa.fa-dashboard
    =link_to new_ticket_path do
      New ticket
-content_for :dashboard_nav do
  active
.col-sm-7
  .panel.panel-primary
    .panel-heading
      %h3.panel-title Create ticket
    .panel-body
      .col-lg-12
        =form_for @ticket, method: :put, role: "form" do |f|
          =render partial: "ticket_form", locals:{f:f}
          .form-group
            =f.submit "Update", class: "btn btn-default"
.col-sm-5
  .panel.panel-success
    .panel-heading
      %h3.panel-title Info
    .panel-body
      .col-lg-12

app/views/tickets/get_next_ticket_history.js.erb
<%if @next_histories.count > 0%>
    $("#ticket_history_element").prepend(
            '<%=j render partial: "ticket_history_line", collection: @next_histories, as: :history%>'
    );
    $.can_load_ticket_history = true;
<%end%>

Waypoint.refreshAll();

app/views/tickets/index.html.haml
-content_for :page_header do
  Dashboard
-content_for :sub_header do
  Tickets main page
-content_for :dashboard_nav do
  active
.col-lg-12.text-center
  .panel.panel-default
    .panel-body
      =link_to "New ticket", new_ticket_path
.col-lg-12.text-center
  .panel.panel-default
    .panel-body
      =form_tag tickets_path, method: :get do
        =label_tag :email
        =email_field_tag :email
        =submit_tag "Show Tickets"
-if @tickets
  .col-sm-7
    .panel.panel-primary
      .panel-heading
        %h3.panel-title Tickets
      .panel-body
        .table-responsive
          %table.table.table-bordered.table-hover.table-striped
            %thead
              %tr
                %th Ticket_id
                %th Title
                %th Status
                %th ProblemType
                %th Comments
                %th Actions
            %tbody
              -@tickets.each do |ticket|
                %tr{style: "background-color: #{ticket.status.color}"}
                  %td=ticket.id
                  %td=ticket.title
                  %td=ticket.status.name
                  %td=ticket.problem_type.name
                  %td=link_to ticket.comments.count, email_ticket_path(ticket.id, email_param)
                  %td
                    =link_to "Show", email_ticket_path(ticket.id, email_param)
                    |
                    =link_to "Edit", edit_email_ticket_path(ticket.id, email_param)
          =will_paginate @tickets, renderer: BootstrapPagination::Rails
  .col-sm-5
    .panel.panel-success
      .panel-heading
        %h3.panel-title
          %i.fa.fa-clock-o.fa-fw
          Last Comments
      .panel-body
        .table-responsive
          -@last_comments.each do |comment|
            =link_to email_ticket_path(comment.commentable_id, email_param) do
              .well
                =comment.text

-#<div id="page-wrapper">
-#
-#  <div class="container-fluid">
-#
-#    <!-- Page Heading -->
-#    <div class="row">
-#      <div class="col-lg-12">
-#        <h1 class="page-header">
-#          Forms
-#        </h1>
-#        <ol class="breadcrumb">
-#          <li>
-#            <i class="fa fa-dashboard"></i>  <a href="index.html">Dashboard</a>
-#          </li>
-#          <li class="active">
-#            <i class="fa fa-edit"></i> Forms
-#          </li>
-#        </ol>
-#      </div>
-#    </div>
-#    <!-- /.row -->
-#
-#    <div class="row">
-#      <div class="col-lg-6">
-#
-#        <form role="form">
-#
-#          <div class="form-group">
-#            <label>Text Input</label>
-#            <input class="form-control">
-#            <p class="help-block">Example block-level help text here.</p>
-#          </div>
-#
-#          <div class="form-group">
-#            <label>Text Input with Placeholder</label>
-#            <input class="form-control" placeholder="Enter text">
-#          </div>
-#
-#          <div class="form-group">
-#            <label>Static Control</label>
-#            <p class="form-control-static">email@example.com</p>
-#          </div>
-#
-#          <div class="form-group">
-#            <label>File input</label>
-#            <input type="file">
-#          </div>
-#
-#          <div class="form-group">
-#            <label>Text area</label>
-#            <textarea class="form-control" rows="3"></textarea>
-#          </div>
-#
-#          <div class="form-group">
-#            <label>Checkboxes</label>
-#            <div class="checkbox">
-#              <label>
-#                <input type="checkbox" value="">Checkbox 1
-#              </label>
-#            </div>
-#            <div class="checkbox">
-#              <label>
-#                <input type="checkbox" value="">Checkbox 2
-#              </label>
-#            </div>
-#            <div class="checkbox">
-#              <label>
-#                <input type="checkbox" value="">Checkbox 3
-#              </label>
-#            </div>
-#          </div>
-#
-#          <div class="form-group">
-#            <label>Inline Checkboxes</label>
-#            <label class="checkbox-inline">
-#              <input type="checkbox">1
-#            </label>
-#            <label class="checkbox-inline">
-#              <input type="checkbox">2
-#            </label>
-#            <label class="checkbox-inline">
-#              <input type="checkbox">3
-#            </label>
-#          </div>
-#
-#          <div class="form-group">
-#            <label>Radio Buttons</label>
-#            <div class="radio">
-#              <label>
-#                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>Radio 1
-#              </label>
-#            </div>
-#            <div class="radio">
-#              <label>
-#                <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">Radio 2
-#              </label>
-#            </div>
-#            <div class="radio">
-#              <label>
-#                <input type="radio" name="optionsRadios" id="optionsRadios3" value="option3">Radio 3
-#              </label>
-#            </div>
-#          </div>
-#
-#          <div class="form-group">
-#            <label>Inline Radio Buttons</label>
-#            <label class="radio-inline">
-#              <input type="radio" name="optionsRadiosInline" id="optionsRadiosInline1" value="option1" checked>1
-#            </label>
-#            <label class="radio-inline">
-#              <input type="radio" name="optionsRadiosInline" id="optionsRadiosInline2" value="option2">2
-#            </label>
-#            <label class="radio-inline">
-#              <input type="radio" name="optionsRadiosInline" id="optionsRadiosInline3" value="option3">3
-#            </label>
-#          </div>
-#
-#          <div class="form-group">
-#            <label>Selects</label>
-#            <select class="form-control">
-#              <option>1</option>
-#              <option>2</option>
-#              <option>3</option>
-#              <option>4</option>
-#              <option>5</option>
-#            </select>
-#          </div>
-#
-#          <div class="form-group">
-#            <label>Multiple Selects</label>
-#            <select multiple class="form-control">
-#              <option>1</option>
-#              <option>2</option>
-#              <option>3</option>
-#              <option>4</option>
-#              <option>5</option>
-#            </select>
-#          </div>
-#
-#          <button type="submit" class="btn btn-default">Submit Button</button>
-#          <button type="reset" class="btn btn-default">Reset Button</button>
-#
-#        </form>
-#
-#      </div>
-#      <div class="col-lg-6">
-#        <h1>Disabled Form States</h1>
-#
-#        <form role="form">
-#
-#          <fieldset disabled>
-#
-#            <div class="form-group">
-#              <label for="disabledSelect">Disabled input</label>
-#              <input class="form-control" id="disabledInput" type="text" placeholder="Disabled input" disabled>
-#            </div>
-#
-#            <div class="form-group">
-#              <label for="disabledSelect">Disabled select menu</label>
-#              <select id="disabledSelect" class="form-control">
-#                <option>Disabled select</option>
-#              </select>
-#            </div>
-#
-#            <div class="checkbox">
-#              <label>
-#                <input type="checkbox">Disabled Checkbox
-#              </label>
-#            </div>
-#
-#            <button type="submit" class="btn btn-primary">Disabled Button</button>
-#
-#          </fieldset>
-#
-#        </form>
-#
-#        <h1>Form Validation</h1>
-#
-#        <form role="form">
-#
-#          <div class="form-group has-success">
-#            <label class="control-label" for="inputSuccess">Input with success</label>
-#            <input type="text" class="form-control" id="inputSuccess">
-#          </div>
-#
-#          <div class="form-group has-warning">
-#            <label class="control-label" for="inputWarning">Input with warning</label>
-#            <input type="text" class="form-control" id="inputWarning">
-#          </div>
-#
-#          <div class="form-group has-error">
-#            <label class="control-label" for="inputError">Input with error</label>
-#            <input type="text" class="form-control" id="inputError">
-#          </div>
-#
-#        </form>
-#
-#        <h1>Input Groups</h1>
-#
-#        <form role="form">
-#
-#          <div class="form-group input-group">
-#            <span class="input-group-addon">@</span>
-#            <input type="text" class="form-control" placeholder="Username">
-#          </div>
-#
-#          <div class="form-group input-group">
-#            <input type="text" class="form-control">
-#            <span class="input-group-addon">.00</span>
-#          </div>
-#
-#          <div class="form-group input-group">
-#            <span class="input-group-addon"><i class="fa fa-eur"></i></span>
-#            <input type="text" class="form-control" placeholder="Font Awesome Icon">
-#          </div>
-#
-#          <div class="form-group input-group">
-#            <span class="input-group-addon">$</span>
-#            <input type="text" class="form-control">
-#            <span class="input-group-addon">.00</span>
-#          </div>
-#
-#          <div class="form-group input-group">
-#            <input type="text" class="form-control">
-#            <span class="input-group-btn"><button class="btn btn-default" type="button"><i class="fa fa-search"></i></button></span>
-#          </div>
-#
-#        </form>
-#
-#        <p>For complete documentation, please visit <a href="http://getbootstrap.com/css/#forms">Bootstrap's Form Documentation</a>.</p>
-#
-#      </div>
-#    </div>
-#    <!-- /.row -->
-#
-#  </div>
-#  <!-- /.container-fluid -->
-#
-#  </div>

app/views/tickets/new.html.haml
-content_for :page_header do
  Create Ticket
-content_for :sub_header do
  New ticket page
-content_for :current_page_breadcrumb do
  %i.fa.fa-dashboard
    =link_to new_ticket_path do
      New ticket
-content_for :dashboard_nav do
  active
.col-sm-7
  .panel.panel-primary
    .panel-heading
      %h3.panel-title Create ticket
    .panel-body
      .col-lg-12
        =form_for @ticket, method: :post, role: "form" do |f|
          .form-group
            =f.label :email
            =f.email_field :email, class: "form-control"
          .form-group
            =f.label :user_name
            =f.text_field :user_name, class: "form-control"
          .form-group
            =f.label :problem_type_id
            =f.select :problem_type_id, options_from_collection_for_select(ProblemType.active_problem_types, "id", "name"), {prompt: "Select Problem Type"}, class: "form-control"
          .form-group
            =f.label :title
            =f.text_field :title, class: "form-control"
          .form-group
            =f.label :text
            =f.text_area :text, class: "form-control"
          .form-group
            =f.submit "Create", class: "btn btn-default"
.col-sm-5
  .panel.panel-success
    .panel-heading
      %h3.panel-title Info
    .panel-body
      .col-lg-12

app/views/tickets/show.html.haml
-content_for :page_header do
  Show Ticket
-content_for :sub_header do
  ticket page
-content_for :current_page_breadcrumb do
  %i.fa.fa-dashboard
    =link_to email_ticket_path(@ticket.id, email_param) do
      Show Ticket
.col-sm-7
  .panel.panel-primary
    .panel-heading
      %h3.panel-title Ticket info
    .panel-body
      -if @ticket.admin_user
        =label_tag :ownership
        .well
          %b
            =@ticket.admin_user.email
      =label_tag :problem_type
      .well
        =@ticket.problem_type.name
      =label_tag :status
      .well{style: "background-color: #{@ticket.status.color}"}
        =@ticket.status.name
      =label_tag :title
      .well
        =@ticket.title
      =label_tag :text
      .well
        =@ticket.text
      %hr
      =form_for @comment, url: comment_path(@ticket.id), method: :post do |f|
        =f.label "Comment Text"
        .well
          =f.text_area :text, class: "form-control"
        =f.submit "Comment", class: "btn btn-default"
      %hr
      =label_tag :comments
      =@ticket.comments.count
      .ticket_comments
        =render partial: "comments/comment_line", collection: @comments, as: :comment
        #ticket_comments_element
.col-sm-5
  .panel.panel-success
    .panel-heading
      %h3.panel-title
        %i.fa.fa-clock-o.fa-fw
        Ticket history
    .panel-body
      .col-lg-12
        .ticket_history
          =render partial: "ticket_history_line", collection: @ticket_histories, as: :history
          #ticket_history_element