config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "home#index"

  get "ticket/:id/mail/:email", to: "tickets#show", as: "email_ticket"
  get "edit_ticket/:id/mail/:email", to: "tickets#edit", as: "edit_email_ticket"
  resources :tickets do
    member do
      resource :comment
      get "load_next_comments", to: "comments#get_next_ticket_comments", as: "get_next_ticket_comments"
      get "load_next_history", to: "tickets#get_next_ticket_history", as: "get_next_ticket_history"
    end
  end

end

app/views/layouts/_links_for_scripts.html.haml
=text_field_tag "get_next_ticket_comments", get_next_ticket_comments_ticket_path(@ticket.id) if @ticket && !@ticket.new_record?
=text_field_tag "get_next_ticket_history", get_next_ticket_history_ticket_path(@ticket.id) if @ticket && !@ticket.new_record?

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{:href => "/"} SB Admin
  %ul.nav.navbar-right.top-nav
    %li.dropdown
      %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
        %i.fa.fa-user
        =email_param.presence
        %b.caret
      %ul.dropdown-menu
        %li
          %a{:href => "#"}
            %i.fa.fa-fw.fa-user
            Profile
        %li
          %a{:href => "#"}
            %i.fa.fa-fw.fa-envelope
            Inbox
        %li
          %a{:href => "#"}
            %i.fa.fa-fw.fa-gear
            Settings
        %li.divider
        %li
          %a{:href => "#"}
            %i.fa.fa-fw.fa-power-off
            Log Out
  / Sidebar Menu Items - These collapse to the responsive navigation menu on small screens
  .collapse.navbar-collapse.navbar-ex1-collapse
    %ul.nav.navbar-nav.side-nav
      %li{class: (yield(:home_nav))}
        =link_to root_path do
          %i.fa.fa-fw.fa-desktop
          Home
      %li{class: (yield(:dashboard_nav))}
        =link_to tickets_path(email: params[:email]) do
          %i.fa.fa-fw.fa-dashboard
          Dashboard
      %li
        =link_to new_admin_user_session_path do
          %i.fa.fa-fw.fa-user
          Admin Panel
      -#%li
      -#  %a{:href => "charts.html"}
      -#    %i.fa.fa-fw.fa-bar-chart-o
      -#    Charts
      -#%li
      -#  %a{:href => "tables.html"}
      -#    %i.fa.fa-fw.fa-table
      -#    Tables
      -#%li
      -#  %a{:href => "forms.html"}
      -#    %i.fa.fa-fw.fa-edit
      -#    Forms
      -#%li
      -#  %a{:href => "bootstrap-elements.html"}
      -#    %i.fa.fa-fw.fa-desktop
      -#    Bootstrap Elements
      -#%li
      -#  %a{:href => "bootstrap-grid.html"}
      -#    %i.fa.fa-fw.fa-wrench
      -#    Bootstrap Grid
      -#%li
      -#  %a{"data-target" => "#demo", "data-toggle" => "collapse", :href => "javascript:;"}
      -#    %i.fa.fa-fw.fa-arrows-v
      -#    Dropdown
      -#    %i.fa.fa-fw.fa-caret-down
      -#  %ul#demo.collapse
      -#    %li
      -#      %a{:href => "#"} Dropdown Item
      -#    %li
      -#      %a{:href => "#"} Dropdown Item
      -#%li
      -#  %a{:href => "blank-page.html"}
      -#    %i.fa.fa-fw.fa-file
      -#    Blank Page
      -#%li
      -#  %a{:href => "index-rtl.html"}
      -#    %i.fa.fa-fw.fa-dashboard
      -#    RTL Dashboard

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SupportIssueTracking
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{rel:"shortcut icon", href:"/assets/ruby-icon.png", type:"image/png"}
  %body
    .hidden
      =render "layouts/links_for_scripts"
    #wrapper
      =render "layouts/nav"
      #page-wrapper
        .container-fluid
          .row
            .col-lg-12
              %h1.page-header
                =yield(:page_header)
                %small=yield(:sub_header)
              -if flash[:alert]
                .alert.alert-danger
                  %strong Alert!
                  =flash[:alert]
              -if flash[:notice]
                .alert.alert-success
                  %strong Success!
                  =flash[:notice]
              %ol.breadcrumb
                = render_breadcrumbs :tag => :li, separator: ""
          .row
            = yield